server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-order-service
  http:
    encoding:
      force: true
      charset: UTF-8

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
